#!/bin/bash
#This script is executed every time your instance is spawned.

# Clone the planq repo and get user_init up to date
cd
cd my_data
rm -rf planq
git clone https://github.com/tihomir-kit/planq
cp ./planq/user_init ./user_init # Ensure we have the latest version of user_init

# Append planq .bashrc to .bashrc if it's not already there
if ! grep -q "planq" ~/.bashrc; then
  echo "" >> ~/.bashrc
  echo "# Planq additions to .bashrc" >> ~/.bashrc
  echo "source ~/my_data/planq/.bashrc" >> ~/.bashrc
fi

# Reload .bashrc
. ~/.bashrc