#!/bin/bash

echo "
https://gtfobins.github.io/ (GTFOBins)
https://gchq.github.io/CyberChef/ (CyberChef)
https://book.hacktricks.xyz/welcome/readme (HackTricks)
https://github.com/swisskyrepo/PayloadsAllTheThings (PayloadsAllTheThings)
https://github.com/TheBinitGhimire/Web-Shells (Web-Shells)
https://github.com/BlackArch/webshells (webshells - BlackArch)
"