#!/bin/bash
# Download all the bin tools to be served over pyserve

if [ -d "tools" ]; then
  # If tools folder already exists, assume this has already been done, don't do it again
  return
fi

# wget -N # don't download if already downloaded
# gzip -k # don't unpack if already unpacked

mkdir tools
cd tools
wget -N https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy64
wget -N https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
wget -N https://github.com/carlospolop/PEASS-ng/releases/download/refs%2Fpull%2F260%2Fmerge/winPEASx64.exe
wget -N https://github.com/int0x33/nc.exe/blob/master/nc.exe # 32-bit?
wget -N https://github.com/int0x33/nc.exe/blob/master/nc64.exe
wget -N https://raw.githubusercontent.com/BlackArch/webshells/master/php/php-reverse-shell.php -O reverse-shell.php
wget -N https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_linux_386.gz
gzip -dk chisel_1.7.7_linux_386.gz
wget -N https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_linux_amd64.gz
gzip -dk chisel_1.7.7_linux_amd64.gz
cp ~/my_data/planq/tools/* .
cd ..