#!/bin/bash
# Install a bunch of tools missing from the base image

sudo apt update

# /usr/share/payloadsallthethings
# /usr/share/seclists
sudo apt install -y \
  payloadsallthethings \
  seclists \
  xrdp \
  sqlitebrowser \
  mongodb-database-tools \
  pwncat

# Install Python tools
pip3 install git-dumper

# Install GO tools (line-by-line required becuase of some GO Install restrictions)
go install -v github.com/hakluke/hakrawler@latest
go install -v github.com/fullstorydev/grpcui/cmd/grpcui@latest
go install -v github.com/jpillora/chisel@latest
go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

# go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
# go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
# go install -v github.com/projectdiscovery/katana/cmd/katana@latest
# go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
