#!/bin/bash

echo "
https://gtfobins.github.io/ (GTFOBins)
https://gchq.github.io/CyberChef/ (CyberChef)
https://www.revshells.com/ (RevShells)
https://book.hacktricks.xyz/welcome/readme (HackTricks)
https://github.com/swisskyrepo/PayloadsAllTheThings (PayloadsAllTheThings)
https://github.com/danielmiessler/SecLists (SecLists)
https://github.com/TheBinitGhimire/Web-Shells (WebShells - TheBinitGhimire)
https://github.com/BlackArch/webshells (WebShells - BlackArch)
"